name: tic-tac-toe
app: tic-tac-toe

replicaCount: 1

image:
  repository: ghcr.io/emmanuelogar/devsecops-demo
  tag: sha-b457b4465692f69639a2401c9ff89c0b6d4b96b7
  pullPolicy: Always

imagePullSecrets:
  name: github-container-registry

containerPort: 80

resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.2"
    memory: "256Mi"

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  host: tic-tac-toe.example.com
  path: /
  annotations: {}
  tls:
    enabled: false
    secretName: tic-tac-toe-tls
